# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Infinite Image Classifier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infinite Image Classifier
  pod 'Tatsi'
  pod 'Firebase/Firestore', '7.2-M1'
  pod 'Firebase/Storage', '7.2-M1'
  pod 'UnsplashPhotoPicker', '~> 1.1.1'
  pod 'Firebase/Functions', '7.2-M1'
  pod 'Firebase/Analytics', '7.2-M1'
end
